/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 .\golden.gltf 
Author: SonnyG1 (https://sketchfab.com/SonnyG1)
License: CC-BY-SA-4.0 (http://creativecommons.org/licenses/by-sa/4.0/)
Source: https://sketchfab.com/3d-models/anti-oloid-69ca982a4ebb4976845030dbff301bc6
Title: Anti Oloid
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import { useRef } from 'react'
import { useFrame } from '@react-three/fiber'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/golden.gltf')

  const group = useRef();

  useFrame(()=>{
    if(group.current){
      group.current.rotation.x += 0.01;
      group.current.rotation.y += 0.02;
    }
  })

  return (
    <group {...props} dispose={null} position={[0,0,0]} scale={1.5} ref={group}>
      <group>
        <mesh geometry={nodes.Anti_Oloid_Material_0.geometry} material={materials.Material} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
    </group>
  )
}

useGLTF.preload('/golden.gltf')
